### DISCUSSION TITLE
[Kavita] Data Attributes for HTML tags

### DISCUSSION THREAD

**Discussion by sammy-ette** [Kareadita/Kavita#2574] [Ideas]
### Idea Description

This feature is meant to extend styling.
> [Data attributes](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) allow us to store extra information on standard, semantic HTML elements without other hacks such as non-standard attributes, or extra properties on DOM.

Adding this to elements for things like tags, genres, age rating, etc. make it possible to easily style certain elements.

Example: a tag with `data-tag="gore"` can be styled in CSS with a red color like so:
```css
elem[data-tag="gore"] {
	background-color: red;
}
```

Or, one can add a :heart: after the Romance genre:
```css
.genre[data-genre="romance"] .genre-text:after {
	content: '❤️';
}
```

What I think this should be applied to:
- Tags
- Genres
- Collections
- Language
- Age Rating
- *maybe* People (Publisher, Writer, etc)

### Duration of Using Kavita

A few months now.

### Idea Category

Feature Enhancement

### Agreement

- [X] I agree that this is solely for submitting ideas, and I will search for existing ideas before posting.
