### ISSUE TITLE
Docker image stays in "starting" state

### ISSUE THREAD

**Issue by ignazioc** [Kareadita/Kavita#1265]
**Describe the bug**
When running the docker image with docker compose, the container stays on status "starting" even when it becomes active

**To Reproduce**
1. Use the docker-compose.yaml suggested on the doc
```
version: '3.9'
services:
    kavita:
        image: kizaing/kavita:latest
        volumes:
            - ./manga:/manga
            - ./data:/kavita/config
        environment:
            - TZ=Europe/Berlin
        ports:
            - "5000:5000"
        restart: unless-stopped
 ```
3. Start the container with `docker compose up -d`
4. Inspect the status of the container with `docker ps` and look at the kavita container. On the column "status" you see " (health: starting)"
5. The container is responsive, I can see the UI on the browser, but the container is still "starting"

**Expected behavior**
I expect that when the service starts, then the status is not "starting" anymore.

**Desktop (please complete the following information):**
 - OS: Linux / Ubuntu / Docker
 - Docker version: `Docker version 20.10.16, build aa7e414`
 - docker image: `latest` 

**Additional context**
Why I bother about the status? well, I'm running the containers behind traefik and the routes are not created until the container is not on ready status.
