### ISSUE TITLE
Books get removed and added each scan without anything changing.

### ISSUE THREAD

**Issue by garthski** [Kareadita/Kavita#1757]
**Describe the bug**
Can't figure out why this one is happening. Some books disappear one one scan, reappear on the next then disappear again on the one after. For example of the bug, i am using Re:Zero light novels as the main one that i notice it happening to. One scan it will just show one volume (5), then on a scan it will remove volume 5 but add in the other volumes I have, then on another scan it will remove those volumes but volume 5 will be added back in.

Logs showing books getting added: https://pastebin.com/7aVNH9ua
Logs showing books getting removed: https://pastebin.com/DX1fpwYF

**To Reproduce**
Scanning Library

**Expected behavior**
Books should only be getting removed if they don't exist anymore or can't read their metadata etc?

**Screenshots**
![Scan 1](https://user-images.githubusercontent.com/569794/214307047-e9d2bab5-12a4-4b04-9ecd-e6e40fa19ca8.png)
![Scan 2](https://user-images.githubusercontent.com/569794/214307204-b2144a36-33af-4da6-9f2f-52d3695e271c.png)

**Desktop (please complete the following information):**
 - OS: OpenMediaVault - Docker
 - Browser: N/A - not browser related
 - Version [e.g. 22] 0.6.1.0

**Additional context**
Book folder is managed via Calibre, metadata is all correct for each book and there's no difference that should be the cause of this issue, 

`/books/Tappei Nagatsuk/Re_ Zero - Starting Life in Another (350)/Re_ Zero - Starting Life in Ano - Tappei Nagatsuk.epub`

`<meta name="calibre:title_sort" content="Re: Zero - Starting Life in Another World - Vol. 05"/>
    <meta name="calibre:series" content="Re:ZERO -Starting Life in Another World-"/>
    <meta name="calibre:series_index" content="5.0"/>`

`/books/Tappei Nagatsuki/Re_ Zero - Starting Life in Another (349)/Re_ Zero - Starting Life in Ano - Tappei Nagatsuki.epub`

`<meta name="calibre:title_sort" content="Re: Zero - Starting Life in Another World - Vol. 06"/>
    <meta name="calibre:series" content="Re:ZERO -Starting Life in Another World-"/>
    <meta name="calibre:series_index" content="6.0"/>`

Docker:
```
---
version: "3.0"
services:
  kavita:
    image: kizaing/kavita:latest
    container_name: kavita
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
    volumes:
      - /docker/kavita:/kavita/config
      - /srv/mergerfs/share/manga:/manga
      - /srv/mergerfs/share/ebooks:/books
    ports:
      - 5000:5000
    restart: unless-stopped
```
