### ISSUE TITLE
Kavita creates folder as root instead of as user 1000:1000 (using LSIO image)

### ISSUE THREAD

**Issue by eswiig** [Kareadita/Kavita#2870]
### What happened?

Kavita creates /home/asusnuc/docker/kavita/ under root and /home/asusnuc/docker/kavita/manga under user asusnuc (1000:1000).

```
services:
    kavita:
        image: lscr.io/linuxserver/kavita:latest    
        container_name: kavita
        volumes:
            - /home/asusnuc/docker/kavita/manga:/manga
            - ./data:/kavita/config
        environment:
          PUID: 1000
          PGID: 1000
          TZ: Europe/Oslo
        ports:
            - "5000:5000"
        restart: unless-stopped
```

### What did you expect?

/home/asusnuc/docker/kavita folder to be created as non root so I get write access in /home/asusnuc/docker/kavita/manga as user asusnuc.

because /home/asusnuc/docker/kavita is created as root, I don't have write privileges with user asusnuc in /home/asusnuc/docker/kavita/manga.

very inconvenient as I prefer to run as my go-to user for read/write access to my NAS.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.0 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```
───────────────────────────────────────
      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝
   Brought to you by linuxserver.io
───────────────────────────────────────
To support the app dev(s) visit:
Kavita: https://opencollective.com/kavita
To support LSIO projects visit:
https://www.linuxserver.io/donate/
───────────────────────────────────────
GID/UID
───────────────────────────────────────
User UID:    1000
User GID:    1000
───────────────────────────────────────
```

### Additional Notes
