### ISSUE TITLE
1% cpu usage on idle

### ISSUE THREAD

**Issue by RA341** [Kareadita/Kavita#3127]
### What happened?

I am running the LSIO Kavita image, and it always has ~1% CPU usage, even when no clients are connected and no tasks are running. Is this expected behavior, a bug, or did I mess up my config? 

I do have folder watch disabled

docker compose:
```
  kavita:
    container_name: kavita
    image: lscr.io/linuxserver/kavita:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${appdata}/kavita/config:/config
      - ${media}/:/media
    ports:
      - 5000:5000
    restart: unless-stopped
``` 

Portainer/ docker stats around 20 minutes of monitoring, no tasks are running; no clients are connected.

![image](https://github.com/user-attachments/assets/7d68b747-1e4f-4606-9d5d-c0c0bb945e2b)

It may be hard to see because of a random spike, the CPU usage is consistent at around 1%

### What did you expect?

It should not use the CPU if no tasks are running or no clients are connected.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None
