### ISSUE TITLE
Ebook CSS is not respected

### ISSUE THREAD

**Issue by Redst0neFlux** [Kareadita/Kavita#3467]
### What happened?

When I open an ebook that has css defined in it (eg colored text and text backgrounds), Kavita overwrites this to fit the color theme.

### What did you expect?

I would like to either have a fifth theme that has fewer defaults (like the white theme with the following removed)
```css
.book-content *:not(input), .book-content *:not(select), .book-content *:not(code), .book-content *:not(:link), .book-content *:not(.ngx-toastr) {
  color: black !important;
}

.book-content code {
  color: #e83e8c !important;
}

.book-content :link, .book-content a {
  color: #8db2e5 !important;
}

.book-content img, .book-content img[src] {
z-index: 1;
filter: brightness(0.85) !important;
background-color: initial !important;
}


.book-content *:not(code), .book-content *:not(a) {
    background-color: white;
    box-shadow: none;
    text-shadow: none;
    border-radius: unset;
    color: #dcdcdc !important;
}
```

It would also be great to be able to define custom reader themes, like we can customise the home page. 

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.4.2 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Additional Notes

Running on a Raspberry Pi, through Nginx
