### ISSUE TITLE
Users unable to access reading lists via OPDS or create reading lists

### ISSUE THREAD

**Issue by spicedreams0x** [Kareadita/Kavita#3651]
### What happened?

I created a reading list as an admin user and promoted it, other users are able to view it on the web interface but can't access it via OPDS (406 error). Additionally other users seem to be unable to create reading lists on their own despite having permissions.

To reproduce the error, I created a new user with admin role, permission to full library, and "No Restriction" for Age Rating. With this user if I navigate to the OPDS endpoint for a particular reading list (https://<url>/api/opds/<api_key_new_user>/reading-list/36) in the browser I get a 406 error but if I try to navigate to a series (https://<url>/api/opds/<api_key_new_user>/series/245) I get the XML file back fine.

Accessing the reading list in the browser with my own account (https://<url>/api/opds/<api_key_my_user>/reading-list/36) works fine and returns the XML. With the newly created admin user if I navigate to an Issue on the Kavita frontend and try to create a reading list by "Add to Reading List" I get a 400 Error "You are not permitted to this operation".
<img width="777" alt="Image" src="https://github.com/user-attachments/assets/a6c4b991-7cc5-461f-8444-f33da2c17c5c" />

### What did you expect?

Other users are able to access reading lists via OPDS and able to create reading lists.

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

0.8.5.11 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2025-03-17 21:09:02.297 -07:00  64] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/opds/<user_api_key>/reading-list/38 responded 406 in 2.7982 ms

[Kavita] [2025-03-17 21:14:23.393 -07:00  70] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/opds/<user_api_key>/series/245 responded 200 in 107.3252 ms
```

### Additional Notes

docker-compose.yml contents
```yaml
  kavita:
    image: jvmilazz0/kavita:latest    # Using the stable branch from the official dockerhub repo.
    container_name: kavita
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
        - "/data/comics/sorted:/comics"          # location is in a NFS mounted drive
        - "/home/docker_stuff/kavita_config/db:/kavita/config"  
    environment:
        - TZ=America/Los_Angeles
    ports:
        - "5000:5000"
    restart: unless-stopped
```
