### ISSUE TITLE
Mixed media type serie in filesystem are duplicated in Kavita

### ISSUE THREAD

**Issue by papalouf** [Kareadita/Kavita#3815]
### What happened?

Hello, 
Maybe more a question than an issue. 
In my library folder (/books) , I have a serie's subfolder (/books/"IT manuals") that contains epub AND pdf files. Actually in Kavita, I see 2 series with the name "IT manuals", one with all the epub files, and one with all the pdf files. 
I managed the metadatas of all files with Calibre to ensure the consistency, before exporting them in the right folder following the Kavita's wiki folder structure page. 

### What did you expect?

All the files (epub AND PDF) from a serie's folder in my library should be visible in the same serie in Kavita webUI. 

### Kavita Version Number - If you don't see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell

```

### Additional Notes

Docker compose used in Portainer : 

```
services:
  ptolemaios_kavita:
    image: jvmilazz0/kavita:nightly
    container_name: ptolemaios_kavita
    volumes:
        - /var/www/Kavita/libray/manga:/manga
        - /var/www/Kavita/libray/comics:/comics
        - /var/www/Kavita/libray/books:/books
        - /var/www/Kavita/data:/kavita/config     
    environment:
        - TZ=Europe/Paris
        - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      - frontend

networks:
  frontend:
    external: true
    name: internal_loop
```
