### ISSUE TITLE
Fail to start in a Raspberry pi 4 (raspbian 10 buster)

### ISSUE THREAD

**Issue by ruidfigueiredo** [Kareadita/Kavita#821]
> Please put as much information as possible to help me understand your issue. OS, browser, version are very important!
```
lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```

> **Describe the bug**

![image](https://user-images.githubusercontent.com/1956584/144517143-8317a8c1-fc1e-4f61-8367-12387ed80f72.png)

> **To Reproduce**

Just do a docker-compose up

**Expected behavior**
That Kavita actually starts

**Comment by majora2007** [comment]
The core dumped means that Kavita expected one architecture and found another and couldn't run. What's interesting is you're using docker AND that we have many users in our discord that use Raspberry Pis. 

I would ask if you could join the discord do so we can debug with support. I think Github Issue will be difficult to work on and I'm not the best at docker myself.

**Comment by ruidfigueiredo** [comment]
Tried on latest version o Raspberry Pi OS:
```
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye
```
And it works fine here. It's just on buster that it doesn't.

**Comment by majora2007** [comment]
One of our users has found the underlying issue:
https://github.com/dotnet/dotnet-docker/issues/3253

Essentially, the workaround for this issue is to run the docker container with privileged for this version of the Pi. 

```
version: '3'
services:
    kavita:
        image: kizaing/kavita:latest
        privileged: true
        container_name: kavita
        volumes:
            - ./manga:/manga
            - ./data:/kavita/config
        ports:
            - "5000:5000"
        restart: unless-stopped
```

This should fix your issue. A user has already tested this out and confirmed.
