### ISSUE TITLE
accessing through Traefik results in "404 page not found"

### ISSUE THREAD

**Issue by daviddoji** [Kareadita/Kavita#859]
**Describe the bug**
I'm trying to setup Kavita as a replacement for calibre-web in my stack of microservices. 
I have set-up a docker-compose file for kavita using Traefik as reverse proxy but I'm getting "page not found" when trying to access the container.
Traefik is setup correctly. I could also see that the container is up and running in Portainer

my `docker-compose` file:
```
# KAVITA ==> Alternative to Calibre-web
  kavita:
    image: kizaing/kavita:0.4.9
    container_name: kavita
    restart: unless-stopped
    networks:
      - media_network
    volumes:
      - ./kavita/config:/kavita/config
      - /media/Storage_Server/Calibre/books:/books
      - /media/Storage_Server/Calibre/comics:/comics
    labels:
      - traefik.enable=true
      - traefik.http.routers.kavita.rule=Host(`library.my_domain.com`)
      - traefik.http.routers.kavita.entrypoints=secure
      - traefik.http.routers.kavite.tls.certresolver=le
      - traefik.http.services.kavita.loadbalancer.server.port=5000
```

**To Reproduce**
1. Docker-compose up -d using the above compose file
2. Go to `library.my_domain.com`
3. Accept the risks (somehow a certificate is not issued)
4. 404 page not found

**Expected behavior**
I have a bunch of other microservices, all of them using the same docker-compose template file (traefik, portainer, bitwarden, seafile, funkwhale, ...)

**Desktop (please complete the following information):**
 - OS: Docker 19.03.13 running under Ubuntu Server 20.04
 - Browse: Firefox
 - Version: 95.0.1
